namespace Common.Models;

public abstract class ModelBase
{
    /// <summary>
    ///     using as primaryKey and identity column in database
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    ///     using as unique index and identity column for records in database
    /// </summary>
    public uint SeqId { get; set; }

    /// <summary>
    ///     using as XminConcurrencyToken in postgres
    /// </summary>
    public uint Version { get; set; }

    /// <summary>
    ///     has default value of 'true'.
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    ///     default value generated by 'NOW()' function of postgres
    /// </summary>
    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset? ModifiedAt { get; set; }
    public DateTimeOffset? DeletedAt { get; set; }
}